//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySaveApp.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySaveApp.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extention du Logiciel.
        /// </summary>
        public static string BlackListExtension {
            get {
                return ResourceManager.GetString("BlackListExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extention.
        /// </summary>
        public static string BlackListTable {
            get {
                return ResourceManager.GetString("BlackListTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logiciels Metier.
        /// </summary>
        public static string BlackListTitle {
            get {
                return ResourceManager.GetString("BlackListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop.
        /// </summary>
        public static string HomeBreakButton {
            get {
                return ResourceManager.GetString("HomeBreakButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tableau de Bord.
        /// </summary>
        public static string HomeDashBoard {
            get {
                return ResourceManager.GetString("HomeDashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jobs en cours.
        /// </summary>
        public static string HomeJobs {
            get {
                return ResourceManager.GetString("HomeJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string HomeNameTable {
            get {
                return ResourceManager.GetString("HomeNameTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lancer.
        /// </summary>
        public static string HomePlayButton {
            get {
                return ResourceManager.GetString("HomePlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pause.
        /// </summary>
        public static string HomeStopButton {
            get {
                return ResourceManager.GetString("HomeStopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Destination.
        /// </summary>
        public static string HomeTargetTable {
            get {
                return ResourceManager.GetString("HomeTargetTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A propos.
        /// </summary>
        public static string MainAboutUsButton {
            get {
                return ResourceManager.GetString("MainAboutUsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logiciels Metier.
        /// </summary>
        public static string MainBusinessSoftwareButton {
            get {
                return ResourceManager.GetString("MainBusinessSoftwareButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde Complète.
        /// </summary>
        public static string MainCompleteBackUpButton {
            get {
                return ResourceManager.GetString("MainCompleteBackUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde Sequentielle.
        /// </summary>
        public static string MainDifferentialButton {
            get {
                return ResourceManager.GetString("MainDifferentialButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        public static string MainHomeButton {
            get {
                return ResourceManager.GetString("MainHomeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramètres.
        /// </summary>
        public static string MainSettingsButton {
            get {
                return ResourceManager.GetString("MainSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoyer.
        /// </summary>
        public static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paramétre de Chiffrement.
        /// </summary>
        public static string SettingsEncryptions {
            get {
                return ResourceManager.GetString("SettingsEncryptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Anglais.
        /// </summary>
        public static string SettingsEnglishButton {
            get {
                return ResourceManager.GetString("SettingsEnglishButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extension Fichiers Logs.
        /// </summary>
        public static string SettingsExtention {
            get {
                return ResourceManager.GetString("SettingsExtention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Français.
        /// </summary>
        public static string SettingsFrenchButton {
            get {
                return ResourceManager.GetString("SettingsFrenchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue.
        /// </summary>
        public static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taille Max de Sauvegarde.
        /// </summary>
        public static string SettingsMaxSize {
            get {
                return ResourceManager.GetString("SettingsMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parametre.
        /// </summary>
        public static string Settingstitle {
            get {
                return ResourceManager.GetString("Settingstitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de la Sauvegarde.
        /// </summary>
        public static string ViewBackUpName {
            get {
                return ResourceManager.GetString("ViewBackUpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Répértoire Source.
        /// </summary>
        public static string ViewSourcePath {
            get {
                return ResourceManager.GetString("ViewSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repertoire Destination.
        /// </summary>
        public static string ViewTargetPath {
            get {
                return ResourceManager.GetString("ViewTargetPath", resourceCulture);
            }
        }
    }
}
